### ISSUE TITLE
README.md: Dead link

### ISSUE THREAD

**Issue by ghost** [kieraneglin/punchbox#5]
> **Looking for a friendly walkthrough? Check here**

Looks like the friendly walkthrough link is dead:
https://kierancodes.com/blog/page-specific-javascript-in-rails-4

**Comment by kieraneglin** [comment]
Doing your due-diligence, I see 😉

Thank you for bringing this to my attention!  Will fix.

**Comment by kieraneglin** [comment]
Fixed with fb078b9

**Comment by ghost** [comment]
Verification: **Pass**

You're welcome!
